apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: 311420043511.dkr.ecr.us-east-2.amazonaws.com/b12:637e3e7bb90e7393ba793c848a5805eb5dad0044
          ports:
            - containerPort: 3000
